### ISSUE TITLE
feat: add more time filter options in response chart

### ISSUE THREAD

**Issue by chamanbravo** [chamanbravo/upstat#38]
![image](https://github.com/chamanbravo/upstat/assets/76839908/a7f55d06-ffb0-46ce-acc3-5c58bc129801)

add 6 hours and 12 hours
keep 6 hours  as default

**Comment by jeyren95** [comment]
hi can i take this too?

**Comment by chamanbravo** [comment]
> hi can i take this too?

Yeah sure 😊, I'll assign you.

**Comment by jeyren95** [comment]
hi i've spotted an issue while doing this extra feature, regarding the display of timestamps for the heartbeats in the linechart

Example using Singapore time (which is +8 GMT):
1. I create a monitor at 2pm Singapore time
2. Timestamp in DB = 2pm
3. Frontend retrieves heartbeats
4. The heartbeat timestamps are converted to local time again, but by right, they should not be converted again
5. Frontend shows 10pm instead of 2pm

Possible solution to resolve this --> **Always store timestamps in DB as UTC time**
- then on the frontend, we convert the timestamps to the respective local timings (which is already implemented)
- this helps to standardize the timestamps being stored in the DB
- so on the frontend side, regardless of which country the user is from, the timestamps in the chartline will be correct

**Comment by jeyren95** [comment]
here is an example
![image](https://github.com/chamanbravo/upstat/assets/65485512/177d6f05-8b97-404d-b3e1-5e391e53eb0d)

**Comment by chamanbravo** [comment]
@jeyren95 Thank you for pointing this out. I'll solve this.

**Comment by jeyren95** [comment]
i can change to UTC if you want?

**Comment by chamanbravo** [comment]
yeah sure, thank you for the initiative.
